version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - bank-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    depends_on:
      - mysql
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    networks:
      - bank-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        REACT_APP_BACKEND_URI: https://SolidBank.local/api/
    container_name: frontend
    stdin_open: true
    tty: true
    depends_on:
      - backend
    networks:
      - bank-network

  nginx:
    build: ./nginx
    image: nginx:latest
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    depends_on:
      - frontend
      - backend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - bank-network

volumes:
  mysql_data:

networks:
  bank-network:
    driver: bridge
